# Generated by Django 2.2.13 on 2020-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_car',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
